type DashboardOverview {
  stores_stats: StoresStats
  rooms_stats: RoomsStats
  today_activity_total: Int
  recent_issues_total: Int
  branches: Stores
  usage_daily: [RoomUsageDay]
  manager_total: Int
  staff_total: Int
  recent_activity: SystemLogs
}

type Query {
  Dashboard_overview: DashboardOverview
}
