type Store {
  _id: ID
  code_store: String
  name_store: String
  code_headquarter: String
  address: String
  employees_count: Int
  rooms_count: Int
}

type Stores {
  data: [Store]
  total: Int
}

type BranchDistributionItem {
  name: String
  code: String
  value: Int
  percent: Float
}

type StoresStats {
  total_branches: Int
  total_staff: Int
  total_rooms: Int
  branch_distribution: [BranchDistributionItem]
  room_distribution: [BranchDistributionItem]
}

type StoreExportFile {
  filename: String
  base64: String
}

type Query {
  Stores(select: select): Stores
  Stores_export(select: select): StoreExportFile
  Stores_stats: StoresStats
}

type Mutation {
  Store_create(
    code_store: String
    name_store: String!
    code_headquarter: String
    address: String
  ): Store
  Store_update(
    _id: ID!
    code_store: String
    name_store: String
    code_headquarter: String
    address: String
  ): Store
  Store_delete(_id: ID!): Boolean
}
