type User {
  _id: ID
  code: String
  username: String
  full_name: String
  mail: String
  phone: String
  avatar: String
  infor: JSON
  role: String
  is_super_admin: Boolean
  is_display: Boolean
  permission: String
  status: Int
  FILE_AVATAR: File
  LAST_ACTIVE: Date
}

type Query {
  User (_id: ID): User
}

type Mutation {
  User_self_update(
    password: String
    old_password: String
    full_name: String
    mail: String
    phone: String
    avatar: String
    infor: JSON
  ): User
}
